ballcat:
  pay:
    bitcoin:
      omni:
        endpoints: mainnet
      enabled: true
    ethereum:
      infura:
        endpoints: mainnet
        # 正式运营请使用自己的 project id, 这个随时可能失效
        project-id: b6066b4cfce54e7384ea38d52f9260ac
    tronscan:
      endpoints: mainnet
      enabled: true
    ali:
      sandbox: true
      dev:
        app-id: 1122334
        private-key: '***'
        alipay-public-key: '***'
        notify-url: https://www.baidu.com
        return-url: https://www.baidu.com

management:
  endpoints:
    web:
      exposure:
        include: '*'